# Generated by Django 3.1.14 on 2023-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=50)),
                ('ratePerHour', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
