# Generated by Django 3.1.14 on 2023-05-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityName',
            field=models.CharField(max_length=100),
        ),
    ]
