# Generated by Django 4.2.1 on 2023-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20230527_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facilityName',
            new_name='facility_name',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='ratePerHour',
            new_name='rate_per_hour',
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
