# Generated by Django 4.2.1 on 2023-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_rename_facilityname_facility_facility_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
