# Generated by Django 4.2.1 on 2023-09-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_alter_facility_facility_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility_name',
            new_name='facilityName',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='rate_per_hour',
            new_name='ratePerHour',
        ),
    ]
