# Generated by Django 4.2.1 on 2023-09-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_rename_facility_name_facility_facilityname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facilityName',
            new_name='facilityname',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='ratePerHour',
            new_name='rateperhour',
        ),
    ]
