# Generated by Django 4.2.1 on 2023-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_setting_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_facility',
            name='facility',
            field=models.CharField(max_length=100, unique='facility'),
        ),
    ]
