# Generated by Django 4.2.1 on 2023-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_alter_setting_facility_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeMainRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.FloatField()),
                ('num_pc', models.IntegerField()),
                ('num_attendies', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(default='this is the description', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypePromoRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('promo_details', models.CharField(max_length=500)),
                ('new_rate', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeSubRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='this is the default', max_length=500)),
            ],
        ),
    ]
