# Generated by Django 4.2.1 on 2023-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0012_usertypemainrules_usertypepromorules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityMainRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.FloatField()),
                ('num_pc', models.IntegerField()),
                ('num_attendies', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySubRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
