# Generated by Django 4.2.1 on 2023-10-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0014_facilitymainrules_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityMainRules',
            new_name='Facility_MainRules',
        ),
        migrations.RenameModel(
            old_name='FacilitySubRules',
            new_name='Facility_SubRules',
        ),
    ]
