# Generated by Django 4.2.1 on 2023-10-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0016_rename_title_facility_mainrules_titles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility_MainRules',
        ),
        migrations.DeleteModel(
            name='Facility_SubRules',
        ),
    ]
