# Generated by Django 4.2.1 on 2023-10-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0017_delete_facility_mainrules_delete_facility_subrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility_MainRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique='title')),
            ],
        ),
    ]
