# Generated by Django 4.2.1 on 2023-10-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0022_rename_titles_facility_mainrules_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility_MainRules',
        ),
    ]
