# Generated by Django 4.2.1 on 2023-10-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0025_facilitymainrules_delete_facility_mainrules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityMainRules',
            new_name='Facility_MainRules',
        ),
    ]
