# Generated by Django 4.2.1 on 2023-10-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0026_rename_facilitymainrules_facility_mainrules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility_MainRules',
            new_name='FacilityMainRules',
        ),
    ]
