# Generated by Django 4.2.1 on 2023-10-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0027_rename_facility_mainrules_facilitymainrules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility_SubRules',
        ),
        migrations.DeleteModel(
            name='FacilityMainRules',
        ),
    ]
