# Generated by Django 4.2.1 on 2023-10-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0029_facility_subrules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility_SubRules',
            new_name='Facility_Mainrules',
        ),
    ]
