# Generated by Django 4.2.1 on 2023-10-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0030_rename_facility_subrules_facility_mainrules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility_Mainrules',
        ),
    ]
