# Generated by Django 4.2.1 on 2023-10-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0034_remove_facility_mainrules_facility_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_mainrules',
            name='facility_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.setting_facility'),
        ),
        migrations.AddField(
            model_name='facility_subrules',
            name='facility_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.setting_facility'),
        ),
    ]
