# Generated by Django 4.2.1 on 2023-10-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0035_facility_mainrules_facility_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_mainrules',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='facility_subrules',
            name='facility_id',
        ),
    ]
