# Generated by Django 4.2.1 on 2023-10-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0036_remove_facility_mainrules_facility_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_mainrules',
            name='facility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility_subrules',
            name='facility',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
