# Generated by Django 4.2.1 on 2023-10-09 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0037_facility_mainrules_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facility_mainrules',
            name='num_pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facility_mainrules',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='facility_mainrules',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
