# Generated by Django 4.2.1 on 2023-10-09 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0038_facility_created_at_facility_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_facility',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='setting_facility',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
