# Generated by Django 4.2.1 on 2023-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0043_facility_mainrules_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_mainrules_set',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facility_mainrules_set',
            name='num_attendies',
            field=models.IntegerField(default=0),
        ),
    ]
