# Generated by Django 4.2.1 on 2023-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0044_alter_facility_mainrules_set_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_mainrules_set',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
