# Generated by Django 4.2.1 on 2023-10-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0045_alter_facility_mainrules_set_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_subrules',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
