# Generated by Django 4.2.1 on 2023-10-23 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0050_datepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('facility', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('custmer_name', models.CharField(max_length=100)),
                ('num_attendies', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('attendie_name', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('add_payment', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='DatePreference',
        ),
    ]
