# Generated by Django 4.2.1 on 2023-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0051_revenue_transaction_delete_datepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_days', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50)),
                ('every_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Revenue_Transaction',
        ),
    ]
