# Generated by Django 4.2.1 on 2023-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0054_revenue_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue_transaction',
            name='facility',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revenue_transaction',
            name='num_attendies',
            field=models.IntegerField(default=0),
        ),
    ]
