# Generated by Django 4.2.1 on 2023-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0055_revenue_transaction_facility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue_transaction',
            old_name='custmer_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='revenue_transaction',
            name='add_payment',
        ),
        migrations.AddField(
            model_name='revenue_transaction',
            name='charge_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='revenue_transaction',
            name='facility_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='revenue_transaction',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
    ]
