# Generated by Django 4.2.1 on 2023-10-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0057_calendarevent_sched_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sched_Type',
        ),
    ]
