# Generated by Django 4.2.1 on 2023-10-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0058_delete_sched_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sched_Type',
            fields=[
                ('type_sched', models.CharField(max_length=100, primary_key=True, serialize=False, unique='type_sched')),
            ],
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='type_sched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.sched_type'),
        ),
    ]
