# Generated by Django 4.2.1 on 2023-10-24 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0060_remove_calendarevent_date_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
