# Generated by Django 4.2.1 on 2023-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0065_rename_charge_payment_revenue_transaction_add_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='selected_days',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('7', 'Saturday'), ('8', 'Sunday'), ('first_week', '1st Week of Month')], max_length=10),
        ),
    ]
