# Generated by Django 4.2.1 on 2023-10-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0066_alter_calendarevent_selected_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='facility',
            new_name='facilities',
        ),
    ]
