# Generated by Django 4.2.1 on 2023-10-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0067_rename_facility_calendarevent_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='facilities',
            new_name='facility',
        ),
    ]
