# Generated by Django 4.2.1 on 2023-11-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0068_rename_facilities_calendarevent_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_facility',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
    ]
