# Generated by Django 4.2.1 on 2023-11-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0069_alter_setting_facility_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_datetime', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('add_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.FloatField(default=0.0)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_booking', models.FloatField(default=0.0)),
                ('charge_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility')),
            ],
        ),
    ]
