# Generated by Django 4.2.1 on 2023-11-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0073_alter_facility_mainrules_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_facility',
            name='facility',
        ),
    ]
