# Generated by Django 4.2.1 on 2023-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0075_setting_facility_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='add_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
