# Generated by Django 4.2.1 on 2023-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0076_alter_transaction_add_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
