# Generated by Django 4.2.1 on 2023-11-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0077_transaction_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_facility',
            name='mainrules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility_mainrules_set'),
        ),
        migrations.AlterField(
            model_name='setting_facility',
            name='promorules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility_promorules_set'),
        ),
        migrations.AlterField(
            model_name='setting_facility',
            name='subrules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility_subrules_set'),
        ),
    ]
