# Generated by Django 4.2.1 on 2023-11-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0078_alter_setting_facility_mainrules_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting_Facility',
        ),
    ]
