# Generated by Django 4.2.1 on 2023-11-08 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0082_alter_setting_usertype_mainrules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_usertype',
            name='mainrules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.usertype_mainrules_set'),
        ),
        migrations.AlterField(
            model_name='setting_usertype',
            name='promorules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.usertype_promorules_set'),
        ),
        migrations.AlterField(
            model_name='setting_usertype',
            name='subrules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.usertype_subrules_set'),
        ),
    ]
