# Generated by Django 4.2.1 on 2023-11-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0084_user_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_usertype',
            name='user_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.user_type'),
        ),
    ]
