# Generated by Django 4.2.1 on 2023-11-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0085_alter_setting_usertype_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_usertype',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.user_type'),
        ),
    ]
