# Generated by Django 4.2.1 on 2023-11-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0087_alter_usertype_mainrules_set_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='facility',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
