# Generated by Django 4.2.5 on 2023-11-24 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0091_facility_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='selected_days',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
