# Generated by Django 4.2.5 on 2023-11-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0092_rename_end_date_calendarevent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype_mainrules',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules_set',
            name='rate',
        ),
    ]
