# Generated by Django 4.2.5 on 2023-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0093_remove_usertype_mainrules_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype_mainrules',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertype_mainrules_set',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
