# Generated by Django 4.2.5 on 2023-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0094_usertype_mainrules_rate_usertype_mainrules_set_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_mainrules',
            name='rate',
            field=models.FloatField(),
        ),
    ]
