# Generated by Django 4.2.5 on 2023-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0095_alter_facility_mainrules_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_facility',
            name='isdeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='setting_usertype',
            name='isdeleted',
            field=models.BooleanField(default=0),
        ),
    ]
