# Generated by Django 4.2.5 on 2023-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0096_setting_facility_isdeleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityname',
            field=models.CharField(max_length=250),
        ),
    ]
