# Generated by Django 4.2.5 on 2023-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0097_alter_facility_facilityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityname',
            field=models.CharField(max_length=250, unique='facility_name'),
        ),
    ]
