# Generated by Django 4.2.5 on 2023-12-17 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0100_remove_facility_promorules_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=250, unique='facility_type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('isdeleted', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='person_rateperhour',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='facility_mainrules',
            name='person_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='facility_mainrules_set',
            name='person_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='facility_promorules',
            name='person_new_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='facility_promorules_set',
            name='person_new_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='setting_facility',
            name='facility_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility_type'),
        ),
    ]
