# Generated by Django 4.2.5 on 2023-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0102_facility_area_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='area_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facility',
            name='person_rateperhour',
            field=models.FloatField(default=0.0),
        ),
    ]
