# Generated by Django 4.2.5 on 2023-12-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0103_alter_facility_area_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='area_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='facility',
            name='person_rateperhour',
            field=models.FloatField(),
        ),
    ]
