# Generated by Django 4.2.5 on 2023-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0104_alter_facility_area_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_promorules',
            name='capacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='facility_promorules_set',
            name='capacity',
            field=models.IntegerField(default=None),
        ),
    ]
