# Generated by Django 4.2.5 on 2023-12-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0105_facility_promorules_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_promorules_set',
            name='capacity',
        ),
    ]
