# Generated by Django 4.2.5 on 2023-12-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0106_remove_facility_promorules_set_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_promorules',
            name='end_date',
        ),
    ]
