# Generated by Django 4.2.5 on 2023-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0107_remove_facility_promorules_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_promorules',
            name='capacity',
        ),
        migrations.AddField(
            model_name='facility_promorules',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
    ]
