# Generated by Django 4.2.5 on 2023-12-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0108_remove_facility_promorules_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_promorules',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
