# Generated by Django 4.2.1 on 2023-05-24 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('computers', models.IntegerField(null=True)),
                ('hasCompters', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('purpose', models.CharField(default='Studying', max_length=50)),
                ('coins', models.FloatField(default=0)),
                ('points', models.FloatField(default=0)),
                ('computers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=100, null=True)),
                ('isUsed', models.BooleanField(default=False, null=True)),
                ('duration', models.FloatField(default=0)),
                ('referenceNo', models.CharField(blank=True, default=uuid.uuid4, max_length=8, unique=True)),
                ('officeName', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Booked', max_length=20, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='api.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.booking')),
            ],
        ),
    ]
