# Generated by Django 4.2.1 on 2023-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
