# Generated by Django 4.2.1 on 2023-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='computers',
            field=models.IntegerField(default=0),
        ),
    ]
