# Generated by Django 4.2.1 on 2023-09-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_referenceno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='hasCompters',
            new_name='hasComputers',
        ),
    ]
