# Generated by Django 4.2.1 on 2023-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_hascompters_venue_hascomputers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venueId',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='venueName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
