# Generated by Django 4.2.1 on 2023-10-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_venueid_booking_venuename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('signInTime', models.TimeField(null=True)),
                ('signOutTime', models.TimeField(null=True)),
                ('isOverstaying', models.BooleanField(default=False, null=True)),
                ('isSignedIn', models.BooleanField(default=False, null=True)),
                ('venueName', models.CharField(max_length=50, null=True)),
                ('venueId', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.booking')),
            ],
        ),
    ]
