# Generated by Django 4.2.1 on 2023-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='rfid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='rfid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
