# Generated by Django 4.2.5 on 2023-11-22 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_attendance_rfid_attendee_rfid_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referenceNo',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=20, unique=True),
        ),
    ]
