# Generated by Django 4.2.5 on 2023-11-22 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_booking_referenceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referenceNo',
            field=models.TextField(blank=True, default=uuid.uuid1, max_length=8, unique=True),
        ),
    ]
