# Generated by Django 4.2.5 on 2023-11-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_id_booking_userid_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='userId',
        ),
    ]
