# Generated by Django 4.1 on 2023-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
