# Generated by Django 4.2.5 on 2023-12-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
