# Generated by Django 4.2.5 on 2023-12-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_booking_area_id'),
        ('api', '0022_booking_isoverstayingcharged'),
    ]

    operations = [
    ]
