# Generated by Django 4.2.5 on 2023-12-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20231216_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='area_id',
        ),
    ]
