# Generated by Django 4.1 on 2023-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccountmodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
