# Generated by Django 4.1 on 2023-12-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_timer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
