# Generated by Django 4.2.5 on 2023-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_user_user_type_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='coin_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='point_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='points_to_give',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
