# Generated by Django 4.2.5 on 2023-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_userprofileinfo_coin_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
