# Generated by Django 4.2.5 on 2023-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminReportLogsModel',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('referenceid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WalkinBookingModel',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('referenceid', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('isOverstaying', models.IntegerField(default=0)),
                ('isTimeEnd', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
