# Generated by Django 4.2.5 on 2023-12-11 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkinbookingmodel',
            name='schedule',
        ),
        migrations.AddField(
            model_name='walkinbookingmodel',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkinbookingmodel',
            name='isOverstaying',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walkinbookingmodel',
            name='isTimeEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walkinbookingmodel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
