# Generated by Django 4.2.5 on 2023-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0002_remove_walkinbookingmodel_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkinbookingmodel',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='walkinbookingmodel',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
