# Generated by Django 4.2.5 on 2023-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0003_alter_walkinbookingmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreportlogsmodel',
            name='endtime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminreportlogsmodel',
            name='starttime',
            field=models.CharField(max_length=100),
        ),
    ]
