# Generated by Django 4.2.5 on 2023-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortransactions',
            name='transactionfield',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
    ]
