# Generated by Django 4.2.5 on 2023-10-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walletAPI', '0003_remove_vendortransactions_transactionfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('reference_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('transactionid', models.CharField(max_length=255)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
