# Generated by Django 4.2.5 on 2023-10-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletAPI', '0004_vendortransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendortransaction',
            old_name='transactionid',
            new_name='transaction_id',
        ),
    ]
