# Generated by Django 4.2.5 on 2023-10-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletAPI', '0005_rename_transactionid_vendortransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortransaction',
            name='currency',
            field=models.CharField(choices=[('points', 'Points'), ('coins', 'Coins')], default='coins', max_length=10),
        ),
        migrations.DeleteModel(
            name='VendorTransactions',
        ),
    ]
