# Generated by Django 4.2.5 on 2023-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletAPI', '0006_vendortransaction_currency_delete_vendortransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortransaction',
            name='transaction_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
